openapi: 3.0.1
servers:
  - url: "https://example.com"
paths:
    /hello/{world}:
        $ref: '#/components/paths/Hello'
components:
    paths:
        Hello:
            $ref: './test.json#/components/paths/World'

        World:
            description: Example description
