openapi: 3.0.1
servers:
  - url: "https://example.com"
paths:
  /hello/{world}:
    get: 
      operationId: say_hello
      parameters: 
        - in: header
          name: Version
          deprecated: true
