openapi: 3.0.1
servers: 
  - url: "https://example.com"
paths:
    /hello/{world}:
        get: 
            operationId: say_hello
            x-pagination: 
                resultsPath: '$response.body#/'
                offset:
                    offsetParam: ''
                    limitParam: ''
                    maxLimit: 100
