[package]
name = "execution_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }

core_entities = { path = "../../entities/core" }
credential_entities = { path = "../../entities/credentials" }
common_data_structures = { path = "../../common/data_structures" }

thiserror = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
tempfile = "3"

