[package]
name = "javascript_runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = { workspace = true }
chrono = { workspace = true }

core_entities = { path = "../../entities/core" }
core_json_compat = { path = "../../common/core_json_compat" }
credential_entities = { path = "../../entities/credentials" }
common_data_structures = { path = "../../common/data_structures" }

thiserror = { workspace = true }
regex = { workspace = true }

mini-v8 = "0.4"



[lints]
workspace = true
