[package]
name = "workflow_runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = { workspace = true }
chrono = { workspace = true }
mlua = { workspace = true, features = ["async", "send"] }
tokio = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }

workflow_engine = { path = "../../prototypes/workflow_engine" }
core_entities = { path = "../../entities/core" }
common_data_structures = { path = "../../common/data_structures" }

[dev-dependencies]
tempfile = "3"
execution_engine = { path = "../../usecases/execution_engine" }
credential_entities = { path = "../../entities/credentials" }
protobuf = { workspace = true }

[lints]
workspace = true
