[package]
name = "service_loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true }
serde_yaml = { workspace = true }
serde_json = { workspace = true, features = ["preserve_order"] }
jsonptr = { workspace = true }
uriparse = "0.6"

credential_entities = { path = "../../entities/credentials" }
core_entities = { path = "../../entities/core" }

thiserror = { workspace = true }
anyhow = { workspace = true }


[lints]
workspace = true
