[package]
name = "oauth_flow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version="0.5.0-rc.2", features=["tls"] }
reqwest = { workspace = true, features = ["json"] }
base64 = { workspace = true }
serde_json = { workspace = true }
jmespath = { workspace = true }

core_entities = { path = "../../entities/core" }
credential_entities = { path = "../../entities/credentials" }

thiserror = { workspace = true }


[lints]
workspace = true
