[package]
name = "lua_runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = { workspace = true }
chrono = { workspace = true }
mlua = { workspace = true }

execution_engine = { path = "../../usecases/execution_engine" }
common_data_structures = { path = "../../common/data_structures" }

thiserror = { workspace = true }

[dev-dependencies]
tempfile = "3"
core_entities = { path = "../../entities/core" }
credential_entities = { path = "../../entities/credentials" }
