[package]
name = "api_caller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { workspace = true, features = ["blocking", "json"] }
serde_json = { workspace = true }
jsonptr = { workspace = true }
base64 = { workspace = true }
http = "0.2"
url = "2.2.0"
chrono = { workspace = true }
urlencoding = "2.1"

execution_engine = { path = "../../usecases/execution_engine" }
core_entities = { path = "../../entities/core" }
credential_entities = { path = "../../entities/credentials" }
common_data_structures = { path = "../../common/data_structures" }

thiserror = { workspace = true }

[dev-dependencies]
tempfile = "3"
protobuf = { workspace = true }
