[package]
name = "apid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = { workspace = true }
tokio = { workspace = true }
notify = { version = "5.1", default-features = false, features = ["macos_kqueue"] }
serde = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

grpc_api = { path = "../../api/grpc_api" }
core_entities = { path = "../../entities/core" }
credential_entities = { path = "../../entities/credentials" }

execution_engine = { path = "../../usecases/execution_engine" }
# query_engine = { path = "../../usecases/query_engine" }

local_directory_catalog = { path = "../../storage/local_directory_catalog" }

api_caller = { path = "../../runners/api_caller" }
python_runner = { path = "../../runners/python_runner" }
javascript_runner = { path = "../../runners/javascript_runner" }
filtered_runner = { path = "../../runners/filtered_runner" }
workflow_runner = { path = "../../runners/workflow_runner" }

common_data_structures = { path = "../../common/data_structures" }

anyhow = { workspace = true, features = ["backtrace"] }
async-trait = { workspace = true }

dhat = { workspace = true }

[dev-dependencies]
tempfile = "3"

[features]
dhat-heap = []
dhat-ad-hoc = []

default = ["python", "javascript", "wrapper"]
python = []
javascript = []
workflow = []
wrapper = []


[lints]
workspace = true
