name: Rust Build
on:
  pull_request:
  push:
    branches: [ "main" ]
    tags: ["v*.*.*"]
    
env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: test
    runs-on: macos-15
    steps: 
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ github.token }}
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install Python
        shell: bash
        run: |
          ./get-python.sh

      - name: Format Check
        run: cargo fmt --all -- --check

      - name: Clippy Check
        run: cargo clippy

      - name: Testing
        run: cargo test
  
  deploy:
    name: deploy
    runs-on: ${{ matrix.os }}
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            os: macos-15
          - target: x86_64-apple-darwin
            os: macos-15
            
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-cargo-
            ${{ runner.os }}-cargo-

      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ github.token }}
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Install Python
        shell: bash
        run: |
          ./get-python.sh ${{ matrix.target }}

      - name: Build Daemon
        env:
          PYO3_CONFIG_FILE: "${{ github.workspace }}/runners/python_runner/pyembedded/pyo3-build-config-file.txt"
        run: cargo build --release --target ${{ matrix.target }} -p apid

      - name: Build CLI
        env:
          PYO3_CONFIG_FILE: "${{ github.workspace }}/runners/python_runner/pyembedded/pyo3-build-config-file.txt"
        run: cargo build --release --target ${{ matrix.target }} -p apicli
      
      - name: Package
        shell: bash 
        run: |
          ./package.sh ${{ github.ref_name }} ${{ matrix.target }}
          
      - name: Publish
        uses: softprops/action-gh-release@v1
        # TODO: if any of the build step fails, the release should be deleted.
        with:
            files: 'dist/apicli*'
          
          
      
  
